[project]
name = "wave"
version = "0.1.0"
description = "Characteristic-Based Split (CBS) simulator"
authors = ["Gabriel Antão <gabrielantao@poli.ufrj.br>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[activation]
scripts = ["setup_env.bash"]

[tasks]
dev-shell = "cd $PIXI_PROJECT_ROOT/simulator/src && julia --project=$PIXI_PROJECT_ROOT/simulator -i $PIXI_PROJECT_ROOT/simulator/startup.jl"
test-unit = "julia --project=$PIXI_PROJECT_ROOT/simulator $PIXI_PROJECT_ROOT/simulator/test/unit_test.jl"
test-case = "julia --project=$PIXI_PROJECT_ROOT/simulator $PIXI_PROJECT_ROOT/simulator/test/validation_test.jl"
wave = "julia --project=$PIXI_PROJECT_ROOT/simulator $PIXI_PROJECT_ROOT/simulator/src/main.jl"

[dependencies]
gmsh = ">=4.12.2,<4.13"
julia = ">=1.10.0,<1.11"
